config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'alphablogs#index'
  get '/home', to: 'alphablogs#index'
  get '/about', to: 'alphablogs#about'

  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  # other to do the users_path post, but we already made the users#new path hence the except
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy' 

  resources :articles

  # we don't want to have the delete action
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories
  has_many :categories, through: :article_categories
  belongs_to :user
  #ensure that every article is created it must have a user
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # calling the set_article method from private only put for edit, update, show, destroy
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  # built method in application controller
  before_action :require_user, except: [:index, :show]
  # this is reference from the private
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # it's up to you to name this but it should be plural like @articles
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    # debugger
    # this line of code you could see the information being pass when you hit the submit button fron /articles/new
    # render plain: params[:article].inspect

    @article = Article.new(article_params)
    # this will ensure that article must have a user_id
    @article.user = current_user
    if @article.save
    #do something
      flash[:success] = "Article was successfully created"
      # redirect to show path
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    # very similar for create function we have to pass the whitelist article_params
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  # whitelist params
  private

    # fix redundancy for @article = Article.find(params[:id]) code in update, edit, show, destroy
    def set_article
      @article = Article.find(params[:id])
    end

    # handling checkbox, we have to whitelist this collection, and this collection is going to be of categories id, an array
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      # we know we can call current_user and @article_user because the before_action :set_article has been set
      # checks if the user is not current user and not an admin but current user is not article user but if current user is admin then this will allow this action
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own article"
        redirect_to root_path
      end
    end
end

app/views/articles/_article.html.erb
<% obj.each do | article | %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg my-article">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <!-- truncating the description -->
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>Created by: <%= article.user.username if article.user %>,
                    <%= time_ago_in_words(article.created_at) %> ago,
                    last updated: <%= time_ago_in_words(article.updated_at) %> ago </small>
          </div>
        </div>
        <% if article.categories.any? %>
            <p> Categories: <%= render article.categories %></p> 
          <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="article-actions">
          <!-- over here give the article object, we're iterating over the @articles so we should only use article -->
          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <!-- the path is very similar to show so you have to code the method delete, also adding the data for confirmation -->
          <%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?" }, class: "btn btn-xs btn-danger" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => { class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title,class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <!-- display all checkbox that are available in application -->
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>

    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center"> Listing all articles</h1>

<div align="center">
  <%= will_paginate %>
</div>
  <%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 class="center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %> </h2>
<div class="well">
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li> Created by:</li>
          <li><%= link_to gravatar_for(@article .user), user_path(@article.user) %></li>
          <li class="article-title">
            <%= link_to  @article.user.username, user_path(@article.user) %>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <!-- simple_format this will display the formatting in creating the description of the article -->
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <!-- rendering here is same with using @article.categories.each do |category| .... end -->
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">
    <!-- # you have to pass the @article to edit -->
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?" }, class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>